### ISSUE TITLE
[BUG] New version available notification incorrectly displaying

### ISSUE THREAD

**Issue by JeffreyDoyle** [Outblock/FRW#63]
### Current Behavior

I have the latest version of Flow Wallet installed on iOS, yet I am seeing the notification prompting me to install the latest update of the application.

### Expected Behavior

- The update notification displays correctly, only if the user doesn't have the latest version of the app.

## Steps to Reproduce

- Install the latest version of Flow Wallet
- Observe the update notification incorrectly displayed

## Expected Outcomes

- [x] The update notification displays correctly, only if the user doesn't have the latest version of the app.

## Platforms

- [x] iOS
- [x] Android

**Comment by JeffreyDoyle** [comment]
@Peppermint1020 to check on progress for android

**Comment by Peppermint1020** [comment]
Confirm with Meng.
The Android version of Flow Wallet does not have this logic issue.
