### ISSUE TITLE
[BUG] Issue connecting to Ankr staking on mobile Flow Wallet

### ISSUE THREAD

**Issue by JeffreyDoyle** [Outblock/FRW#67]
### Current Behavior

Mobile Flow Wallet currently isn't available in Ankr's wallet list, and fails to be able to connect to Ankr staking when selecting to connect with wallet connect.

### Expected Behavior

- Mobile Flow Wallet is available in Ankr staking's wallet list
- Mobile Flow Wallet is able to connect to Ankr staking.

## Steps to Reproduce

- Using Flow Wallet mobile, navigate to Ankr staking https://www.ankr.com/staking/stake/flow/
- Observe Flow Wallet not available in it's wallet list
- Select Wallet Connect
- Select Flow Wallet from the list of wallet options

## Expected Outcomes

- [ ] Investigate why Flow Wallet is not available in the wallet list
- [ ] Investigate why Flow Wallet is not able to connect on mobile when selecting wallet connect
- [ ] If a solution is possible, we resolve the issues
- [ ] Otherwise, provide solution steps we can give to Ankr to resolve the issues.

## Platforms

- [ ] iOS
- [ ] Android

**Comment by Direnyy** [comment]
Hello @JeffreyDoyle  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
