### ISSUE TITLE
[FEATURE] Show correct price information for tokens listed on Punch Swap

### ISSUE THREAD

**Issue by JeffreyDoyle** [Outblock/FRW#72]
## Feature

Punch Swap ( https://swap.kittypunch.xyz/ ) currently supports swapping USDC.e for the various new meme tokens listed on Flow. This establishes a price in USDC for each supported meme token. Today, Flow Wallet displays an incorrect 0$ value for each meme token, which is not the correct value.

Within Flow Wallet, we must use the same pricing information that Punch Swap uses to display the correct value in USD for each meme token, such as AVO. This data is available from the GeckoTerminal DEX API https://www.geckoterminal.com/dex-api , as you can see in use here: https://www.geckoterminal.com/flow-evm/punchswap/pools 

## Expected Outcomes

- [ ] Flow Wallet displays the correct price information, in USD, for each supported meme token

## Platforms

- [ ] iOS
- [ ] Android
- [ ] Extension

**Comment by lmcmz** [comment]
@JeffreyDoyle  Could you help us to get the API key for the coingecko ?
`Analyst`  level API should be good enough for now

**Comment by lmcmz** [comment]
Closes as complete
