### ISSUE TITLE
[BUG] Flow Wallet not displaying as an injected provider on RainbowKit applications

### ISSUE THREAD

**Issue by JeffreyDoyle** [Outblock/FRW#74]
### Current Behavior

- Using the in-app browser, Flow Wallet is not displaying as an injected provider on RainbowKit applications

### Expected Behavior

- Flow Wallet displays as an injected option in RainbowKit applications

## Steps to Reproduce

- Navigate to Punch Swap in the in-app browser
- Selected connect
- Observe Flow Wallet not displayed as an immediate option

## Expected Outcomes

- [ ] Flow Wallet displays as an injected option in RainbowKit applications

## Platforms

- [ ] Extension
- [ ] iOS
- [ ] Android

**Comment by zhouxl** [comment]
I got message is not valid JSON. eg. `"\"{\\\"type\\\":\\\"verify_attestation\\\"}\""`

**Comment by JeffreyDoyle** [comment]
This is resolved by providing dapp configuration. We have an example of how to do so here: https://github.com/Outblock/flow-evm-rainbow/blob/main/component/config.ts#L18-L76
