### ISSUE TITLE
[BUG] Unable to send USDC.e from EVM to Cadence account

### ISSUE THREAD

**Issue by JeffreyDoyle** [Outblock/FRW#75]
### Current Behavior

- Flow Wallet mobile (tested on iOS) is unable to move USDC.e from an EVM to a Cadence account

### Expected Behavior

- Flow Wallet can send any FT between an EVM account to a Cadence account, provided the recipient Cadence account has the required FT vault set up.

## Steps to Reproduce

- Send some USDC.e from an EVM account to a destination Cadence account
- Observe the transaction fail.

## Expected Outcomes

- [ ] Flow Wallet can send any FT between an EVM account to a Cadence account, provided the recipient Cadence account has the required FT vault set up.

## Platforms

- [ ] Extension
- [ ] iOS
- [ ] Android

## Details:

@Peppermint1020 -- Please test this workflow across all platforms, including for both FT and NFT tokens.

**Comment by Peppermint1020** [comment]
This issue already solved in all platforms.
