### ISSUE TITLE
[BUG] Transaction history text display issues

### ISSUE THREAD

**Issue by JeffreyDoyle** [Outblock/FRW#79]
### Current Behavior

- When viewing transaction history, text sometimes overlaps and becomes illegible. 

![image (22)](https://github.com/user-attachments/assets/304c56b2-8426-40c8-ad68-560f0a19f28c)
![image (21)](https://github.com/user-attachments/assets/514e96e3-eaf9-4384-b8e1-fe0c6d999c70)

### Expected Behavior

- Text is always legible across all pages of the app.

## Steps to Reproduce

- Navigate to transaction history
- Execute some transactions that results in long text display
- Observe the text overlapping, becoming illegible.

## Expected Outcomes

- [ ] Text is always legible across all pages of the app.

## Platforms

- [ ] Extension
- [ ] iOS
- [ ] Android

**Comment by zzggo** [comment]
![Image](https://github.com/user-attachments/assets/54361437-3379-47e6-9bd6-b92e4d966541)

**Comment by Peppermint1020** [comment]
This issue seems solved in prod version 2.5.22.
![Image](https://github.com/user-attachments/assets/7df772e0-99b0-414d-be7f-09c581cc730e)

**Comment by Peppermint1020** [comment]
This issue solved in prod version 2.5.22
![Image](https://github.com/user-attachments/assets/2e959dfd-96e5-41f2-b52d-ed307a5ee87b)
