### ISSUE TITLE
[BUG] Multi-backup freezing during key upload to cloud providers

### ISSUE THREAD

**Issue by JeffreyDoyle** [Outblock/FRW#80]
### Current Behavior

- When backing up to Google Drive / iCloud during multi-backup, the workflow freezes and the user is unable to progress.

### Expected Behavior

- Multi-backup functions as expected and succeeds.

## Steps to Reproduce

- Create a new profile
- Backup the profile using multi-backup
- Select to use Google Drive and iCloud
- Observe the process hang / fail when uploading keys to each provider.

## Expected Outcomes

- [ ] Multi-backup functions as expected and succeeds.

## Platforms

- [ ] Extension
- [ ] iOS (tested on iOS but let's confirm on all platforms)
- [ ] Android

## Details:

Contact @JeffreyDoyle for the address of the user who reported this issue. I'm not including it in the issue for privacy reasons.

**Comment by JeffreyDoyle** [comment]
@zhouxl -- To investigate this issue on iOS.

**Comment by Peppermint1020** [comment]
@JeffreyDoyle 
Hi Jeff, I tested in current version 2.2.11(7) ant cannot reproduced this issue.
Could you reproduced this issue  on your device and export log for developer for troubleshooting

**Comment by JeffreyDoyle** [comment]
I followed up with the user to see which country they were in when the issue happened. I'm also unable to reproduce the issue.

**Comment by JeffreyDoyle** [comment]
We've been unable to reproduce this issue. Closing.
