### ISSUE TITLE
[BUG] Incorrect prompt to claim tokens using a faucet on token detail page

### ISSUE THREAD

**Issue by JeffreyDoyle** [Outblock/FRW#82]
### Current Behavior

- When viewing any token detail page on mainnet, it displays an incorrect prompt to that token using a faucet.

### Expected Behavior

- Prompts to claim tokens using a faucet must never happen on mainnet, as such a faucet does not exist. 
- Only on testnet, when viewing the token detail page for FLOW token can the claim tokens prompt appear.

## Steps to Reproduce

- Aquire any non-FLOW token on mainnet
- Select to view the token detail page for that token
- Observe the prompt to claim that token using a faucet

## Expected Outcomes

- [ ] Prompts to claim tokens using a faucet must never happen on mainnet, as such a faucet does not exist. 
- [ ] Only on testnet, when viewing the token detail page for FLOW token can the claim tokens prompt appear.

## Platforms

- [ ] Extension

## Details:
<img width="387" alt="Screen Shot 2024-11-24 at 12 47 47 PM" src="https://github.com/user-attachments/assets/31982039-97c7-400a-b51e-40951a951a19">

**Comment by JeffreyDoyle** [comment]
@zzggo -- To resolve this issue.

**Comment by Peppermint1020** [comment]
This issue already solved in extension prod version 2.5.22.
Plan to release in this week.
![Image](https://github.com/user-attachments/assets/684ae2a2-5572-416a-9f81-3a14e52f9a83)
