### ISSUE TITLE
[BUG] Token website link fails to open

### ISSUE THREAD

**Issue by JeffreyDoyle** [Outblock/FRW#83]
### Current Behavior

- When a COA is active, on the token detail page, selecting the token's website link fails to open the correct link.

### Expected Behavior

- The correct link opens for every token.
- When a link is unknown for a given token, this action should open its contract's page on flowscan.io

## Steps to Reproduce

- Aquire some BETA token to a COA
- Click the token's website link
- Observe nothing happen. 

## Expected Outcomes

- [ ] The correct link opens for every token.
- [ ] When a link is unknown for a given token, this action should open its contract's page on flowscan.io

## Platforms

- [ ] Extension
- [ ] iOS
- [ ] Android

## Details:

<img width="391" alt="Screen Shot 2024-11-24 at 12 52 43 PM" src="https://github.com/user-attachments/assets/efccd7f8-922d-4326-911f-4aaaa6002aca">

**Comment by JeffreyDoyle** [comment]
@Peppermint1020 -- To ensure this was included in the latest extension release.

**Comment by Peppermint1020** [comment]
This issue already solved in Extension prod version 2.5.22

**Comment by Peppermint1020** [comment]
The link for flow token in COA seems wrong.
https://github.com/user-attachments/assets/34726add-a456-4009-a0d8-8a2c8e200034

**Comment by Peppermint1020** [comment]
This issue already solved in Extension prod version 2.5.22
