### ISSUE TITLE
[BUG] Incorrect token links

### ISSUE THREAD

**Issue by JeffreyDoyle** [Outblock/FRW#90]
### Current Behavior

- Certain tokens (eg: USDC.e) have links to incorrect pages. For example, USDC.e links to axlUSDC. 

### Expected Behavior

- Token links always link to the correct token listings. (eg: USDC.e links to circle.com

## Steps to Reproduce

- Navigate to USDC.e token detail page.
- Select the token link.
- Observe the user brought to the axlUSD page.

## Expected Outcomes

- [ ] Tokens always link to the correct pages.

## Platforms

- [ ] Extension
- [ ] iOS
- [ ] Android

**Comment by caosbad** [comment]
https://github.com/Outblock/token-list-jsons/commit/8d35fa9df81f91c81e06f8c52b41c0dd6068c501

**Comment by lmcmz** [comment]
Closes as @caosbad update the link
